# Generated by Django 5.0.6 on 2024-12-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_transbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoscompras',
            name='id_compra',
            field=models.CharField(max_length=100),
        ),
    ]
